"""自动迁移-10081841

Revision ID: c8d035048a7c
Revises: 5ce48c9e86ec
Create Date: 2026-10-08 18:41:08.201218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d035048a7c'
down_revision: Union[str, None] = '5ce48c9e86ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_portfolio_snapshot',
    sa.Column('total_twd', sa.Numeric(precision=20, scale=2), nullable=False, comment='总资产(TWD)'),
    sa.Column('total_usdt', sa.Numeric(precision=20, scale=2), nullable=False, comment='总资产(USDT)'),
    sa.Column('twd_rate', sa.Numeric(precision=12, scale=4), nullable=False, comment='USDT/TWD 汇率'),
    sa.Column('accounts', sa.JSON(), nullable=False, comment='各账户总额 [{exchange, type, total}]'),
    sa.Column('failures', sa.JSON(), nullable=False, comment='读取失败的账户；非空时总额少算了这些账户'),
    sa.Column('occurred_time', sa.DateTime(timezone=True), nullable=False, comment='快照时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_portfolio_snapshot')),
    comment='Bot资产快照表'
    )
    with op.batch_alter_table('bot_portfolio_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_bot_portfolio_snapshot_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_portfolio_snapshot_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_portfolio_snapshot_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_portfolio_snapshot_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_portfolio_snapshot_occurred_time'), ['occurred_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_portfolio_snapshot_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_portfolio_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_portfolio_snapshot_uuid'))
        batch_op.drop_index(batch_op.f('ix_bot_portfolio_snapshot_occurred_time'))
        batch_op.drop_index(batch_op.f('ix_bot_portfolio_snapshot_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bot_portfolio_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_bot_portfolio_snapshot_created_time'))
        batch_op.drop_index('ix_bot_portfolio_snapshot_created_deleted')

    op.drop_table('bot_portfolio_snapshot')
    # ### end Alembic commands ###
