"""自动迁移-10081724

Revision ID: 5ce48c9e86ec
Revises: 0b626fe8cf2f
Create Date: 2026-10-08 17:24:52.203259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce48c9e86ec'
down_revision: Union[str, None] = '0b626fe8cf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_runtime_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.String(length=32), nullable=True, comment='正在解析的网站，与解析无关的日志为空'))
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_site'), ['site'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_runtime_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_site'))
        batch_op.drop_column('site')

    # ### end Alembic commands ###
