"""自动迁移-10081622

Revision ID: 0b626fe8cf2f
Revises: 556100ee3478
Create Date: 2026-10-08 16:22:54.077308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b626fe8cf2f'
down_revision: Union[str, None] = '556100ee3478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_parse_log',
    sa.Column('platform', sa.String(length=16), nullable=False, comment='平台(discord/line)'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='触发方式(auto:自动解析 command:指令)'),
    sa.Column('group_external_id', sa.String(length=64), nullable=True, comment='群组平台侧ID，私聊为空'),
    sa.Column('user_external_id', sa.String(length=64), nullable=True, comment='用户平台侧ID'),
    sa.Column('user_name', sa.String(length=128), nullable=True, comment='用户名称(当时)'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='链接'),
    sa.Column('site', sa.String(length=32), nullable=True, comment='网站'),
    sa.Column('result', sa.String(length=16), nullable=False, comment='结果(success/failed/busy)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误原因'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('file_count', sa.Integer(), nullable=True, comment='文件数'),
    sa.Column('compressed', sa.Boolean(), nullable=True, comment='是否压缩过'),
    sa.Column('occurred_time', sa.DateTime(timezone=True), nullable=False, comment='发生时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_parse_log')),
    comment='Bot解析日志表'
    )
    with op.batch_alter_table('bot_parse_log', schema=None) as batch_op:
        batch_op.create_index('ix_bot_parse_log_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_group_external_id'), ['group_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_occurred_time'), ['occurred_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_site'), ['site'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_user_external_id'), ['user_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_parse_log_uuid'), ['uuid'], unique=True)

    op.create_table('bot_runtime_log',
    sa.Column('source', sa.String(length=16), nullable=False, comment='来源进程(discord/line)'),
    sa.Column('level', sa.String(length=8), nullable=False, comment='等级(info/warn/error)'),
    sa.Column('message', sa.Text(), nullable=False, comment='内容'),
    sa.Column('occurred_time', sa.DateTime(timezone=True), nullable=False, comment='发生时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_runtime_log')),
    comment='Bot运行日志表'
    )
    with op.batch_alter_table('bot_runtime_log', schema=None) as batch_op:
        batch_op.create_index('ix_bot_runtime_log_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_occurred_time'), ['occurred_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_runtime_log_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_runtime_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_uuid'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_source'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_occurred_time'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_level'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_id'))
        batch_op.drop_index(batch_op.f('ix_bot_runtime_log_created_time'))
        batch_op.drop_index('ix_bot_runtime_log_created_deleted')

    op.drop_table('bot_runtime_log')
    with op.batch_alter_table('bot_parse_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_uuid'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_user_external_id'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_site'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_result'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_platform'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_occurred_time'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_id'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_group_external_id'))
        batch_op.drop_index(batch_op.f('ix_bot_parse_log_created_time'))
        batch_op.drop_index('ix_bot_parse_log_created_deleted')

    op.drop_table('bot_parse_log')
    # ### end Alembic commands ###
