"""自动迁移-10102247

Revision ID: 7d856d6d21b3
Revises: fca0f11bcbd7
Create Date: 2026-10-10 22:47:13.074709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d856d6d21b3'
down_revision: Union[str, None] = 'fca0f11bcbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_dependency',
    sa.Column('project', sa.String(length=64), nullable=False, comment='项目，如 yohaneowo-bot'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='依赖名称'),
    sa.Column('category', sa.String(length=32), nullable=True, comment='分类，由上报方决定，如 后端、前端、前端开发工具、Docker 镜像'),
    sa.Column('kind', sa.String(length=16), nullable=False, comment='来源类型(npm/pypi/github/docker/none)'),
    sa.Column('source', sa.String(length=256), nullable=False, comment='查询标识：npm/PyPI 包名、GitHub owner/repo、Docker 镜像'),
    sa.Column('usage', sa.String(length=255), nullable=True, comment='用途说明'),
    sa.Column('critical', sa.Boolean(), nullable=False, comment='是否重点依赖(由上报方标记，坏了影响最大)'),
    sa.Column('installed_version', sa.String(length=64), nullable=True, comment='项目实际使用的版本(上报)'),
    sa.Column('reported_time', sa.DateTime(timezone=True), nullable=False, comment='最近一次上报时间'),
    sa.Column('latest_version', sa.String(length=64), nullable=True, comment='上游最新版本'),
    sa.Column('upstream_updated_time', sa.DateTime(timezone=True), nullable=True, comment='上游最后更新时间'),
    sa.Column('archived', sa.Boolean(), nullable=False, comment='上游是否已封存(GitHub)'),
    sa.Column('outdated', sa.Boolean(), nullable=False, comment='实际版本是否落后于最新版本'),
    sa.Column('major_behind', sa.Boolean(), nullable=False, comment='是否落后一个大版本(升级可能有不兼容改动)'),
    sa.Column('vulnerable', sa.Boolean(), nullable=False, comment='实际版本是否有已知漏洞(OSV)'),
    sa.Column('vulnerabilities', sa.JSON(), nullable=True, comment='已知漏洞 [{id, aliases, summary, severity, fixed}]'),
    sa.Column('vuln_severity', sa.String(length=16), nullable=True, comment='已知漏洞的最高等级(CRITICAL/HIGH/MODERATE/LOW)'),
    sa.Column('fix_version', sa.String(length=64), nullable=True, comment='修复全部已知漏洞要升级到的版本'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态(healthy/warning/risk/unknown/error/skipped)'),
    sa.Column('check_error', sa.Text(), nullable=True, comment='最近一次检查的错误'),
    sa.Column('checked_time', sa.DateTime(timezone=True), nullable=True, comment='最近一次检查时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_dependency')),
    sa.UniqueConstraint('project', 'name', name='uq_project_dependency_project_name'),
    comment='项目依赖表'
    )
    with op.batch_alter_table('project_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_dependency_category'), ['category'], unique=False)
        batch_op.create_index('ix_project_dependency_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_project'), ['project'], unique=False)
        batch_op.create_index('ix_project_dependency_status_deleted', ['status', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_dependency_vulnerable'), ['vulnerable'], unique=False)

    op.create_table('project_dependency_check',
    sa.Column('dependency_id', sa.Integer(), nullable=False, comment='依赖ID'),
    sa.Column('installed_version', sa.String(length=64), nullable=True, comment='当时的实际版本'),
    sa.Column('latest_version', sa.String(length=64), nullable=True, comment='当时的最新版本'),
    sa.Column('upstream_updated_time', sa.DateTime(timezone=True), nullable=True, comment='当时查到的上游最后更新时间'),
    sa.Column('archived', sa.Boolean(), nullable=False, comment='是否已封存'),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False, comment='当时的已知漏洞数'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态'),
    sa.Column('check_error', sa.Text(), nullable=True, comment='错误'),
    sa.Column('checked_time', sa.DateTime(timezone=True), nullable=False, comment='检查时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['dependency_id'], ['project_dependency.id'], name=op.f('fk_project_dependency_check_dependency_id_project_dependency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_dependency_check')),
    comment='项目依赖检查记录表'
    )
    with op.batch_alter_table('project_dependency_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_dependency_check_checked_time'), ['checked_time'], unique=False)
        batch_op.create_index('ix_project_dependency_check_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_check_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_check_dependency_id'), ['dependency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_check_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_check_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_project_dependency_check_status_deleted', ['status', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependency_check_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_dependency_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_uuid'))
        batch_op.drop_index('ix_project_dependency_check_status_deleted')
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_dependency_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_created_time'))
        batch_op.drop_index('ix_project_dependency_check_created_deleted')
        batch_op.drop_index(batch_op.f('ix_project_dependency_check_checked_time'))

    op.drop_table('project_dependency_check')
    with op.batch_alter_table('project_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_dependency_vulnerable'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_uuid'))
        batch_op.drop_index('ix_project_dependency_status_deleted')
        batch_op.drop_index(batch_op.f('ix_project_dependency_project'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependency_created_time'))
        batch_op.drop_index('ix_project_dependency_created_deleted')
        batch_op.drop_index(batch_op.f('ix_project_dependency_category'))

    op.drop_table('project_dependency')
    # ### end Alembic commands ###
