"""自动迁移-10081237

Revision ID: 556100ee3478
Revises: 
Create Date: 2026-10-08 12:37:46.092652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556100ee3478'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_group',
    sa.Column('platform', sa.String(length=16), nullable=False, comment='平台(discord/line)'),
    sa.Column('external_id', sa.String(length=64), nullable=False, comment='平台侧ID(Discord guild ID / LINE groupId)'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='群组名称'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='成员数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('is_joined', sa.Boolean(), nullable=False, comment='bot 是否仍在群内'),
    sa.Column('joined_time', sa.DateTime(timezone=True), nullable=True, comment='加入时间'),
    sa.Column('left_time', sa.DateTime(timezone=True), nullable=True, comment='离开时间'),
    sa.Column('last_active_time', sa.DateTime(timezone=True), nullable=True, comment='最后活动时间'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_group')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_bot_group_platform_external_id'),
    comment='Bot群组表'
    )
    with op.batch_alter_table('bot_group', schema=None) as batch_op:
        batch_op.create_index('ix_bot_group_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_group_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_group_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_group_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_group_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_bot_group_status_deleted', ['status', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_group_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_group_uuid'))
        batch_op.drop_index('ix_bot_group_status_deleted')
        batch_op.drop_index(batch_op.f('ix_bot_group_platform'))
        batch_op.drop_index(batch_op.f('ix_bot_group_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bot_group_id'))
        batch_op.drop_index(batch_op.f('ix_bot_group_created_time'))
        batch_op.drop_index('ix_bot_group_created_deleted')

    op.drop_table('bot_group')
    # ### end Alembic commands ###
