"""新增Bot语音停留记录表

Revision ID: fca0f11bcbd7
Revises: c8d035048a7c
Create Date: 2026-10-10 01:10:46.718287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca0f11bcbd7'
down_revision: Union[str, None] = 'c8d035048a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_voice_session',
    sa.Column('guild_external_id', sa.String(length=64), nullable=False, comment='Discord 服务器ID'),
    sa.Column('channel_external_id', sa.String(length=64), nullable=False, comment='语音频道ID'),
    sa.Column('channel_name', sa.String(length=100), nullable=False, comment='语音频道名称(当时)'),
    sa.Column('user_external_id', sa.String(length=64), nullable=False, comment='用户ID'),
    sa.Column('user_name', sa.String(length=128), nullable=True, comment='用户名称(当时)'),
    sa.Column('user_avatar_url', sa.String(length=512), nullable=True, comment='用户头像URL(当时)'),
    sa.Column('joined_time', sa.DateTime(timezone=True), nullable=False, comment='进入时间'),
    sa.Column('joined_time_estimated', sa.Boolean(), nullable=False, comment='进入时间是否为估计值(bot 启动时人已在频道，用启动时间代替)'),
    sa.Column('left_time', sa.DateTime(timezone=True), nullable=False, comment='离开时间'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='停留秒数'),
    sa.Column('end_reason', sa.String(length=16), nullable=False, comment='结束原因(leave:离开 move:换频道 restart:bot 重启)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_voice_session')),
    comment='Bot语音停留记录表'
    )
    with op.batch_alter_table('bot_voice_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_voice_session_channel_external_id'), ['channel_external_id'], unique=False)
        batch_op.create_index('ix_bot_voice_session_created_deleted', ['created_time', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_end_reason'), ['end_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_guild_external_id'), ['guild_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_joined_time'), ['joined_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_left_time'), ['left_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_user_external_id'), ['user_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_voice_session_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_voice_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_uuid'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_user_external_id'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_left_time'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_joined_time'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_id'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_guild_external_id'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_end_reason'))
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_created_time'))
        batch_op.drop_index('ix_bot_voice_session_created_deleted')
        batch_op.drop_index(batch_op.f('ix_bot_voice_session_channel_external_id'))

    op.drop_table('bot_voice_session')
    # ### end Alembic commands ###
